<?php

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arena_stock_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_simple_stock module.
    case 'help.page.arena_stock':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows commerce_simple_stock.') . '</p>';
      // Here should be details about setting up and using
      return $output;

    default:
  }
}

